name: Discussion update
on:
  discussion:
    types: [created, edited, deleted, labeled, unlabeled]
jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: backend
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update Discussion Database
        run: python discussion_update
        env:
          NUMBER: ${{ github.event.discussion.number }}
          TITLE: ${{ github.event.discussion.title }}
          CREATED_AT: ${{ github.event.discussion.created_at }}
          UPDATED_AT: ${{ github.event.discussion.updated_at }}
          BODY: ${{ github.event.discussion.body }}
          LABELS: ${{ toJson(github.event.discussion.labels.*.name) }}
